import { afterEach, describe, expect, it } from "vitest";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, renameSync, rmSync, statfsSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
// @ts-expect-error Executable JavaScript module.
import { initializeStorage, registerScratch, storageHold, sealScratch, planStorageCleanup, applyStorageCleanup, reserveStorage, releaseStorage } from "../src/native-storage.mjs";
// @ts-expect-error Executable JavaScript module.
import { finalizeScratch, finalizeFailedNativeBuild } from "../src/native-storage-finalize.mjs";
// @ts-expect-error Executable JavaScript module.
import { treeDigest } from "../src/native-state.mjs";

const roots: string[] = [];
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });
function fixture() {
  const root = realpathSync(mkdtempSync(join(tmpdir(), "storage-test-")));
  roots.push(root);
  initializeStorage(root, "task");
  writeFileSync(join(root, "proof.json"), '{"passed":true}');
  return root;
}
function scratch(root: string, id = "attempt", kind = "scratch") {
  mkdirSync(join(root, id));
  writeFileSync(join(root, id, "generated"), "generated bytes");
  registerScratch(root, "task", { id, path: id, kind, purpose: "fixture", evidence: ["proof.json"] });
}

describe("development storage ownership", () => {
  it("keeps evidence and bounded scratch across repeated completed attempts", () => {
    const root = fixture();
    for (let attempt = 0; attempt < 4; attempt++) {
      mkdirSync(join(root, "payload"));
      writeFileSync(join(root, "payload", "runtime"), String(attempt));
      const result = finalizeScratch(root, "task", ["payload"], ["proof.json"]);
      expect(result.removed).toHaveLength(1);
      expect(existsSync(join(root, "payload"))).toBe(false);
      expect(readFileSync(join(root, "proof.json"), "utf8")).toContain("passed");
    }
    expect(planStorageCleanup(root).remove).toEqual([]);
  });

  it("preview is read-only and owner or consumer uncertainty blocks deletion", () => {
    const root = fixture(); scratch(root); sealScratch(root, "task", "attempt");
    storageHold(root, "task", "queued-test", true);
    storageHold(root, "task", "paused-debug", true);
    const before = treeDigest(root);
    expect(planStorageCleanup(root).remove).toEqual([]);
    expect(treeDigest(root)).toBe(before);
    expect(() => applyStorageCleanup(root, "other")).toThrow("owner differs");
    expect(() => applyStorageCleanup(root, "task")).toThrow("consumers");
    storageHold(root, "task", "queued-test", false);
    expect(() => applyStorageCleanup(root, "task")).toThrow("consumers");
    storageHold(root, "task", "paused-debug", false);
    mkdirSync(join(root, "lock"));
    expect(planStorageCleanup(root).remove).toEqual([]);
    expect(() => applyStorageCleanup(root, "task")).toThrow();
  });

  it("keeps real live child work even when its status incorrectly says passed", async () => {
    const root = fixture(); scratch(root);
    const child = spawn(process.execPath, ["-e", "setInterval(()=>{}, 1000)"]);
    try {
      writeFileSync(join(root, "attempt", "run-status.json"), JSON.stringify({ status: "passed", pid: child.pid }));
      expect(() => sealScratch(root, "task", "attempt")).toThrow("running");
    } finally { child.kill(); await once(child, "exit"); }
    writeFileSync(join(root, "attempt", "run-status.json"), JSON.stringify({ status: "running", pid: child.pid }));
    expect(() => sealScratch(root, "task", "attempt")).toThrow("uncertain");
  });

  it.each([".git", "recovery.json", "lock", "backup-references"])("protects source and recovery marker %s", marker => {
    const root = fixture(); scratch(root);
    writeFileSync(join(root, "attempt", marker), "protected");
    expect(() => sealScratch(root, "task", "attempt")).toThrow();
    expect(existsSync(join(root, "attempt", "generated"))).toBe(true);
  });

  it("rejects path escapes, broken links, changed paths, and changed retained evidence", () => {
    const root = fixture(); scratch(root);
    const spec = { id: "bad", purpose: "fixture", evidence: ["proof.json"] };
    expect(() => registerScratch(root, "task", { ...spec, path: "../escape" })).toThrow();
    symlinkSync("/missing-storage-test", join(root, "linked"));
    expect(() => registerScratch(root, "task", { ...spec, path: "linked" })).toThrow("linked");
    sealScratch(root, "task", "attempt");
    writeFileSync(join(root, "attempt", "generated"), "changed");
    expect(() => applyStorageCleanup(root, "task")).toThrow("changed");
    writeFileSync(join(root, "attempt", "generated"), "generated bytes");
    const record = JSON.parse(readFileSync(join(root, "storage.json"), "utf8"));
    writeFileSync(join(root, record.entries[0].retainedEvidence[0].path), "lost evidence");
    expect(() => applyStorageCleanup(root, "task")).toThrow("evidence changed");
  });

  it("preserves scratch after failed evidence export", () => {
    const root = fixture(); scratch(root);
    rmSync(join(root, "proof.json"));
    expect(() => sealScratch(root, "task", "attempt")).toThrow();
    expect(planStorageCleanup(root).keep[0].reason).toBe("active");
  });

  it("resumes interrupted deletion only from the recorded inode and preserved evidence", () => {
    const root = fixture(); scratch(root); sealScratch(root, "task", "attempt");
    const record = JSON.parse(readFileSync(join(root, "storage.json"), "utf8"));
    record.entries[0].status = "removing";
    writeFileSync(join(root, "storage.json"), JSON.stringify(record));
    mkdirSync(join(root, "storage-trash"));
    renameSync(join(root, "attempt"), join(root, "storage-trash", "attempt"));
    rmSync(join(root, "storage-trash", "attempt", "generated"));
    const before = treeDigest(root);
    expect(planStorageCleanup(root).remove).toEqual([]);
    expect(treeDigest(root)).toBe(before);
    expect(applyStorageCleanup(root, "task").removed).toEqual(["attempt"]);
  });

  it("retains one acknowledged failure for seven days and never ages out active work", () => {
    const root = fixture(); scratch(root, "failure", "failed");
    sealScratch(root, "task", "failure");
    scratch(root, "still-active", "failed");
    expect(applyStorageCleanup(root, "task").removed).toEqual([]);
    const later = new Date(Date.now() + 8 * 86400_000);
    expect(applyStorageCleanup(root, "task", later).removed).toEqual(["failure"]);
    expect(existsSync(join(root, "still-active"))).toBe(true);
  });

  it("accounts for reservations from competing builders and never silently expires them", () => {
    const root = fixture();
    const stat = statfsSync(root);
    const free = stat.bavail * stat.bsize;
    const first = reserveStorage(root, "builder-one", Math.floor(free * 0.75), 0);
    expect(() => reserveStorage(root, "builder-two", Math.floor(free * 0.75), 0)).toThrow("capacity");
    expect(() => reserveStorage(root, "builder-one", 0, 0)).toThrow("already");
    expect(() => releaseStorage(root, "unknown")).toThrow("ownership");
    releaseStorage(root, first.token);
    expect(reserveStorage(root, "builder-two", 1, 0).bytes).toBe(1);
  });
});


it("bounds failed local builder attempts as groups while preserving source and reproduction evidence", () => {
  const root = fixture();
  for (let attempt = 0; attempt < 3; attempt++) {
    const build = join(root, `attempt-${attempt}`, "builder");
    mkdirSync(join(build, "source", ".git"), { recursive: true });
    for (const name of ["context", "artifacts", "source/node_modules", "source/dist"]) {
      mkdirSync(join(build, name), { recursive: true });
      writeFileSync(join(build, name, "bytes"), "generated");
    }
    writeFileSync(join(build, "run-status.json"), JSON.stringify({ status: "failed", failure: "fixture" }));
    finalizeFailedNativeBuild(root, "task", build);
    expect(existsSync(join(build, "context"))).toBe(true);
    if (attempt) expect(existsSync(join(root, `attempt-${attempt - 1}`, "builder", "context"))).toBe(false);
    expect(existsSync(join(build, "source", ".git"))).toBe(true);
    expect(existsSync(join(build, "run-status.json"))).toBe(true);
  }
});
