import { afterEach, describe, expect, it, vi } from "vitest";
import { execFileSync, spawn } from "node:child_process";
import { once } from "node:events";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, renameSync, rmSync, statfsSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
// @ts-expect-error Executable JavaScript module.
import { initializeStorage, registerScratch, storageHold, sealScratch, planStorageCleanup, applyStorageCleanup, reserveStorage, releaseStorage, resumeFailedScratch, reserveStageStorage, storageLogicalBytes } from "../src/native-storage.mjs";
// @ts-expect-error Executable JavaScript module.
import { finalizeScratch, finalizeFailedNativeBuild, retainCompletedOperationLog } from "../src/native-storage-finalize.mjs";
// @ts-expect-error Executable JavaScript module.
import { acquireLock, treeDigest, fileDigest } from "../src/native-state.mjs";

const roots: string[] = [];
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });
function fixture() {
  const root = realpathSync(mkdtempSync(join(tmpdir(), "storage-test-")));
  roots.push(root);
  initializeStorage(root, "task");
  writeFileSync(join(root, "proof.json"), '{"passed":true}');
  return root;
}
function scratch(root: string, id = "attempt", kind = "scratch") {
  mkdirSync(join(root, id));
  writeFileSync(join(root, id, "generated"), "generated bytes");
  registerScratch(root, "task", { id, path: id, kind, purpose: "fixture", evidence: ["proof.json"] });
}
function resume(root: string, build: string) {
  const taskUnlock = acquireLock(root);
  const buildUnlock = acquireLock(build);
  try { resumeFailedScratch(root, "task", build); }
  finally { buildUnlock(); taskUnlock(); }
}

describe("development storage ownership", () => {
  it("keeps evidence and bounded scratch across repeated completed attempts", () => {
    const root = fixture();
    for (let attempt = 0; attempt < 4; attempt++) {
      mkdirSync(join(root, "payload"));
      writeFileSync(join(root, "payload", "runtime"), String(attempt));
      const result = finalizeScratch(root, "task", ["payload"], ["proof.json"]);
      expect(result.removed).toHaveLength(1);
      expect(existsSync(join(root, "payload"))).toBe(false);
      expect(readFileSync(join(root, "proof.json"), "utf8")).toContain("passed");
    }
    expect(planStorageCleanup(root).remove).toEqual([]);
  });

  it("preview is read-only and owner or consumer uncertainty blocks deletion", () => {
    const root = fixture(); scratch(root); sealScratch(root, "task", "attempt");
    storageHold(root, "task", "queued-test", true);
    storageHold(root, "task", "paused-debug", true);
    const before = treeDigest(root);
    expect(planStorageCleanup(root).remove).toEqual([]);
    expect(treeDigest(root)).toBe(before);
    expect(() => applyStorageCleanup(root, "other")).toThrow("owner differs");
    expect(() => applyStorageCleanup(root, "task")).toThrow("consumers");
    storageHold(root, "task", "queued-test", false);
    expect(() => applyStorageCleanup(root, "task")).toThrow("consumers");
    storageHold(root, "task", "paused-debug", false);
    mkdirSync(join(root, "lock"));
    expect(planStorageCleanup(root).remove).toEqual([]);
    expect(() => applyStorageCleanup(root, "task")).toThrow();
  });

  it("keeps real live child work even when its status incorrectly says passed", async () => {
    const root = fixture(); scratch(root);
    const child = spawn(process.execPath, ["-e", "setInterval(()=>{}, 1000)"]);
    try {
      writeFileSync(join(root, "attempt", "run-status.json"), JSON.stringify({ status: "passed", pid: child.pid }));
      expect(() => sealScratch(root, "task", "attempt")).toThrow("running");
    } finally { child.kill(); await once(child, "exit"); }
    writeFileSync(join(root, "attempt", "run-status.json"), JSON.stringify({ status: "running", pid: child.pid }));
    expect(() => sealScratch(root, "task", "attempt")).toThrow("uncertain");
  });

  it.each([".git", "recovery.json", "lock", "backup-references"])("protects source and recovery marker %s", marker => {
    const root = fixture(); scratch(root);
    writeFileSync(join(root, "attempt", marker), "protected");
    expect(() => sealScratch(root, "task", "attempt")).toThrow();
    expect(existsSync(join(root, "attempt", "generated"))).toBe(true);
  });

  it("rejects path escapes, broken links, changed paths, and changed retained evidence", () => {
    const root = fixture(); scratch(root);
    const spec = { id: "bad", purpose: "fixture", evidence: ["proof.json"] };
    expect(() => registerScratch(root, "task", { ...spec, path: "../escape" })).toThrow();
    symlinkSync("/missing-storage-test", join(root, "linked"));
    expect(() => registerScratch(root, "task", { ...spec, path: "linked" })).toThrow("linked");
    sealScratch(root, "task", "attempt");
    writeFileSync(join(root, "attempt", "generated"), "changed");
    expect(() => applyStorageCleanup(root, "task")).toThrow("changed");
    writeFileSync(join(root, "attempt", "generated"), "generated bytes");
    const record = JSON.parse(readFileSync(join(root, "storage.json"), "utf8"));
    writeFileSync(join(root, record.entries[0].retainedEvidence[0].path), "lost evidence");
    expect(() => applyStorageCleanup(root, "task")).toThrow("evidence changed");
  });

  it("preserves scratch after failed evidence export", () => {
    const root = fixture(); scratch(root);
    rmSync(join(root, "proof.json"));
    expect(() => sealScratch(root, "task", "attempt")).toThrow();
    expect(planStorageCleanup(root).keep[0].reason).toBe("active");
  });

  it("preserves restricted directory and file modes when sealing evidence", () => {
    const root = fixture();
    mkdirSync(join(root, "stages", "nested"), { recursive: true });
    chmodSync(join(root, "stages"), 0o700);
    chmodSync(join(root, "stages", "nested"), 0o750);
    writeFileSync(join(root, "stages", "nested", "proof.json"), '{"passed":true}');
    chmodSync(join(root, "stages", "nested", "proof.json"), 0o640);
    mkdirSync(join(root, "payload"));
    writeFileSync(join(root, "payload", "generated"), "bytes");
    registerScratch(root, "task", { id: "payload", path: "payload", purpose: "completed TEST", evidence: ["stages"] });
    const digest = treeDigest(join(root, "stages"), { portable: true });
    const sealed = sealScratch(root, "task", "payload");
    expect(treeDigest(join(root, sealed.retainedEvidence[0].path), { portable: true })).toBe(digest);
    expect(applyStorageCleanup(root, "task").removed).toEqual(["payload"]);
    expect(treeDigest(join(root, "stages"), { portable: true })).toBe(digest);
  });

  it("resumes interrupted deletion only from the recorded inode and preserved evidence", () => {
    const root = fixture(); scratch(root); sealScratch(root, "task", "attempt");
    const record = JSON.parse(readFileSync(join(root, "storage.json"), "utf8"));
    record.entries[0].status = "removing";
    writeFileSync(join(root, "storage.json"), JSON.stringify(record));
    mkdirSync(join(root, "storage-trash"));
    renameSync(join(root, "attempt"), join(root, "storage-trash", "attempt"));
    rmSync(join(root, "storage-trash", "attempt", "generated"));
    const before = treeDigest(root);
    expect(planStorageCleanup(root).remove).toEqual([]);
    expect(treeDigest(root)).toBe(before);
    expect(applyStorageCleanup(root, "task").removed).toEqual(["attempt"]);
  });

  it("retains one acknowledged failure for seven days and never ages out active work", () => {
    const root = fixture(); scratch(root, "failure", "failed");
    sealScratch(root, "task", "failure");
    scratch(root, "still-active", "failed");
    expect(applyStorageCleanup(root, "task").removed).toEqual([]);
    const later = new Date(Date.now() + 8 * 86400_000);
    expect(applyStorageCleanup(root, "task", later).removed).toEqual(["failure"]);
    expect(existsSync(join(root, "still-active"))).toBe(true);
  });

  it("accounts for reservations from competing builders and never silently expires them", () => {
    const root = fixture();
    const stat = statfsSync(root);
    const free = stat.bavail * stat.bsize;
    const first = reserveStorage(root, "builder-one", Math.floor(free * 0.75), 0);
    expect(() => reserveStorage(root, "builder-two", Math.floor(free * 0.75), 0)).toThrow("capacity");
    expect(() => reserveStorage(root, "builder-one", 0, 0)).toThrow("already");
    expect(() => releaseStorage(root, "unknown")).toThrow("ownership");
    releaseStorage(root, first.token);
    expect(reserveStorage(root, "builder-two", 1, 0).bytes).toBe(1);
  });
});

it("retires old deletion authority before replacing a failed builder on retry", () => {
  const root = fixture();
  const first = join(root, "a", "builder");
  const fail = (build: string) => {
    mkdirSync(join(build, "context"), { recursive: true });
    writeFileSync(join(build, "context", "generated"), "failed output");
    writeFileSync(join(build, "run-status.json"), JSON.stringify({ status: "failed" }));
    finalizeFailedNativeBuild(root, "task", build);
  };
  fail(first);
  const original = JSON.parse(readFileSync(join(root, "storage.json"), "utf8")).entries[0];
  resume(root, first);
  rmSync(join(first, "context"), { recursive: true });
  fail(first);
  fail(join(root, "b", "builder"));
  const entries = JSON.parse(readFileSync(join(root, "storage.json"), "utf8")).entries;
  expect(entries.find((entry: { id: string }) => entry.id === original.id).status).toBe("superseded");
  expect(existsSync(join(root, original.retainedEvidence[0].path))).toBe(true);
  expect(existsSync(join(first, "context"))).toBe(false);
  expect(existsSync(join(root, "b", "builder", "context"))).toBe(true);
});

it("refuses a retry without both locks, with consumers, or with pending deletion", () => {
  const root = fixture();
  const build = join(root, "builder");
  mkdirSync(join(build, "context"), { recursive: true });
  writeFileSync(join(build, "run-status.json"), JSON.stringify({ status: "failed" }));
  finalizeFailedNativeBuild(root, "task", build);
  expect(() => resumeFailedScratch(root, "task", build)).toThrow();
  storageHold(root, "task", "debug", true);
  expect(() => resume(root, build)).toThrow("consumers");
  storageHold(root, "task", "debug", false);
  const record = JSON.parse(readFileSync(join(root, "storage.json"), "utf8"));
  record.entries[0].status = "removing";
  writeFileSync(join(root, "storage.json"), JSON.stringify(record));
  expect(() => resume(root, build)).toThrow("protected scratch");
  expect(JSON.parse(readFileSync(join(root, "storage.json"), "utf8")).entries[0].status).toBe("removing");
});

it("blocks retry after failed evidence export until the owner completes sealing", () => {
  const root = fixture();
  const build = join(root, "builder");
  mkdirSync(join(build, "context"), { recursive: true });
  const status = JSON.stringify({ status: "failed", failure: "prior generation" });
  writeFileSync(join(build, "run-status.json"), status);
  registerScratch(root, "task", { id: "failed", path: "builder/context", kind: "failed",
    purpose: "failed attempt", evidence: ["builder/run-status.json", "proof.json"] });
  rmSync(join(root, "proof.json"));
  expect(() => sealScratch(root, "task", "failed")).toThrow();
  expect(() => resume(root, build)).toThrow("finish owner finalization");
  expect(readFileSync(join(build, "run-status.json"), "utf8")).toBe(status);
  expect(JSON.parse(readFileSync(join(root, "storage.json"), "utf8")).entries[0].status).toBe("active");
});


it("bounds failed local builder attempts as groups while preserving source and reproduction evidence", () => {
  const root = fixture();
  for (let attempt = 0; attempt < 3; attempt++) {
    const build = join(root, `attempt-${attempt}`, "builder");
    mkdirSync(join(build, "source", ".git"), { recursive: true });
    for (const name of ["context", "artifacts", "source/node_modules", "source/dist"]) {
      mkdirSync(join(build, name), { recursive: true });
      writeFileSync(join(build, name, "bytes"), "generated");
    }
    writeFileSync(join(build, "run-status.json"), JSON.stringify({ status: "failed", failure: "fixture" }));
    finalizeFailedNativeBuild(root, "task", build);
    expect(existsSync(join(build, "context"))).toBe(true);
    if (attempt) expect(existsSync(join(root, `attempt-${attempt - 1}`, "builder", "context"))).toBe(false);
    expect(existsSync(join(build, "source", ".git"))).toBe(true);
    expect(existsSync(join(build, "run-status.json"))).toBe(true);
  }
});


it("keeps operation diagnostics until explicit task completion", async () => {
  const root = fixture();
  mkdirSync(join(root, "logs"));
  for (let attempt = 0; attempt < 3; attempt++) {
    const log = `logs/prepare-${attempt}.log`;
    writeFileSync(join(root, log), `attempt ${attempt}: ${"diagnostic".repeat(10000)}`);
    const reference = retainCompletedOperationLog(root, log, "task", join(root, "draft-controller/log-pool"));
    expect(existsSync(join(root, log))).toBe(false);
    expect(JSON.parse(readFileSync(join(root, `${log}.reference.json`), "utf8"))).toEqual(reference);
    expect(existsSync(join(reference.pool, "objects", reference.objectId, "logs.tar.gz"))).toBe(true);
  }
  expect(readdirSync(join(root, "logs")).every(name => name.endsWith(".reference.json"))).toBe(true);
  // @ts-expect-error Executable JavaScript module.
  const { applyArtifactCleanup, completeRetentionRun } = await import("../src/native-retention.mjs");
  const pool = join(root, "draft-controller/log-pool");
  applyArtifactCleanup(pool, new Date(Date.now() + 31 * 86400000));
  expect(readdirSync(join(pool, "objects"))).toHaveLength(3);
  for (const reference of readdirSync(join(pool, "references"))) completeRetentionRun(pool, reference.replace(/\.json$/, ""), "task");
  applyArtifactCleanup(pool);
  expect(readdirSync(join(pool, "objects"))).toEqual([]);
});

it("stage reservations count concurrent demand and preserve their configured floor", () => {
  const root = fixture(), capacity = join(root, "capacity"); mkdirSync(capacity);
  vi.stubEnv("E2E_CAPACITY_ROOT", capacity);
  try {
    writeFileSync(join(root, "payload"), "12345");
    symlinkSync(join(root, "payload"), join(root, "link"));
    expect(storageLogicalBytes(join(root, "payload"))).toBe(5);
    expect(storageLogicalBytes(join(root, "link"))).toBe(0);
    const reservation = reserveStageStorage("stage-one", root, 1024, 0);
    const disk = statfsSync(capacity), available = disk.bavail * disk.bsize;
    expect(() => reserveStageStorage("stage-two", root, available + 1024 ** 3, 1)).toThrow("Insufficient");
    releaseStorage(reservation.root, reservation.token);
    expect(JSON.parse(readFileSync(join(capacity, "reservations.json"), "utf8")).reservations).toEqual([]);
  } finally { vi.unstubAllEnvs(); }
});

// @ts-expect-error Executable activation lifecycle.
import { systemOperations } from "../src/native-activation.mjs";
it("activation admission measures expanded archives and retains blocked maintenance health", async () => {
  const root = fixture(), capacity = join(root, "capacity"), installDir = join(root, "installed"), stateDir = join(root, "state"), backupRoot = join(root, "backups");
  for (const path of [capacity, installDir, stateDir, backupRoot]) mkdirSync(path);
  writeFileSync(join(installDir, "code"), "1234"); writeFileSync(join(stateDir, "data"), "12345");
  const archive = join(root, "runtime.tar.gz");
  execFileSync("tar", ["-czf", archive, "-C", installDir, "."], { env: { ...process.env, COPYFILE_DISABLE: "1" } });
  const browserArchive = join(root, "browser.tar");
  execFileSync("tar", ["-cf", browserArchive, "-C", stateDir, "."], { env: { ...process.env, COPYFILE_DISABLE: "1" } });
  const browser = { path: browserArchive, sha256: fileDigest(browserArchive) };
  writeFileSync(join(backupRoot, "retention-health.json"), JSON.stringify({ status: "blocked", message: "recovery differs" }));
  const recovery = join(backupRoot, "activation-100-1"); mkdirSync(recovery);
  vi.stubEnv("E2E_CAPACITY_ROOT", capacity); vi.stubEnv("E2E_REQUIRED_FREE_BYTES", "0");
  try {
    const reservation = await systemOperations({ installDir, stateDir, backupRoot, browser }, recovery).reserveCapacity({ artifact: { path: archive, sha256: fileDigest(archive) } });
    expect(reservation.bytes).toBe(2 * (4 + 5 + 4 + 5));
    const admission = JSON.parse(readFileSync(join(recovery, "capacity-admission.json"), "utf8"));
    expect(admission.retentionHealth.status).toBe("blocked");
    releaseStorage(reservation.root, reservation.token);
    vi.stubEnv("E2E_REQUIRED_FREE_BYTES", String(Number.MAX_SAFE_INTEGER));
    await expect(systemOperations({ installDir, stateDir, backupRoot, browser }, recovery).reserveCapacity({ artifact: { path: archive, sha256: fileDigest(archive) } })).rejects.toThrow("retention health: blocked");
    expect(JSON.parse(readFileSync(join(recovery, "capacity-admission.json"), "utf8")).status).toBe("blocked");
  } finally { vi.unstubAllEnvs(); }
});


it("does not start a second archive reader after the first reader fails", async () => {
  const root = fixture(), first = join(root, "first.tar"), second = join(root, "second.tar");
  writeFileSync(first, "corrupt archive"); writeFileSync(second, "second archive");
  const readers: string[] = [];
  let active = 0;
  const run = async (_command: string, args: string[]) => {
    readers.push(args.at(-1)!); active++;
    try { await new Promise(resolve => setTimeout(resolve, 10)); throw new Error("corrupt archive"); }
    finally { active--; }
  };
  const receipt = { artifact: { path: first, sha256: fileDigest(first) }, additionalArtifacts: [{ artifact: { path: second, sha256: fileDigest(second) } }] };
  await expect(systemOperations({ stateDir: root }, root, run).reserveCapacity(receipt)).rejects.toThrow("corrupt archive");
  expect(readers).toEqual([first]);
  expect(active).toBe(0);
});
